"""Auto-generated by NeuroDecomp.

This file is a HONEST PARTIAL decompilation of a hand-compiled
nn.Sequential model.  Every fact below has been independently recovered
from the model's weights -- no algorithm-specific knowledge was used.

Recovered:
  * tokenizer: Recovered ASCII tokenizer: ord(str(x)[:55].ljust(55, '\x00'))
  * initial state: 4 x 32-bit words
  * auxiliary head constants: 3 x 32-bit words
  * body iterations: 63
  * body block size (Linears per iteration): 42
  * rotate gadget: 3 register(s) x 32-bit lanes
  * shift schedule: 63 entries
  * 16-byte equality target: c7ef65233c40aa32c2b9ace37595fa7c
  * AND patterns: 12859 confirmed / 58524 candidate

Pending milestones:
  * per-round K constants for i in [1, 63] (only K[0] recovered, stamped into head's working state)
  * iteration 63 / iteration 64 of the body (absorbed into head/tail/stitching layers; block finder reports 63 of presumably 64 MD5-style rounds)
  * F/G/H/I non-linear round functions and the modular 32-bit adder gadget (visible as bool_and patterns, not yet identified as named operations)
  * input padding scheme (head's input length counting, 0x80 framing byte, length suffix)
  * full codegen: a Python g such that g(s) == model(s) for every s in Sigma^<=55 (waiting on the items above)
  * richer abstract domain (MVP-7.5) to certify the remaining 78% of bool_and candidate patterns

The emitted program will run for parts that have been recovered, and will
raise NotImplementedError where decompilation is still in progress.  As
later milestones land, the stubs get replaced with real Python.
"""
import sys
from dataclasses import dataclass, field
from typing import Sequence


# =============================================================================
# Recovered constants
# =============================================================================

TOKENIZER_LENGTH = 55
TOKENIZER_PAD = '\x00'

INITIAL_STATE_LE = (0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476)
EXTRA_HEAD_CONSTANTS_LE = (0x88888888, 0x10325476, 0xd76aa478)

NUM_BODY_ITERATIONS = 63
SHIFT_SCHEDULE = (7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 7, 12, 17, 22, 5, 9, 14, 20, 5, 9, 14, 20, 5, 9, 14, 20, 5, 9, 14, 20, 4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23, 4, 11, 16, 23, 6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15, 21, 6, 10, 15)
ROTATE_NUM_REGISTERS = 3
ROTATE_NUM_LANES = 32

TARGET_DIGEST_HEX = 'c7ef65233c40aa32c2b9ace37595fa7c'
TARGET_DIGEST_BYTES = bytes.fromhex(TARGET_DIGEST_HEX) if TARGET_DIGEST_HEX else b""

CANDIDATE_AND_COUNT = 58524
CONFIRMED_AND_COUNT = 12859


# =============================================================================
# Recovered tokenizer (fully implemented)
# =============================================================================

def encode(s: str) -> list:
    """Map a string to TOKENIZER_LENGTH ASCII byte values, null-padded."""
    s = str(s)[:TOKENIZER_LENGTH].ljust(TOKENIZER_LENGTH, TOKENIZER_PAD)
    return [ord(c) for c in s]


# =============================================================================
# Pending: per-round constant K[i] for i in [1, NUM_BODY_ITERATIONS]
# =============================================================================

ROUND_CONSTANTS_RECOVERED = {}      # Pending MVP-8


def K(i: int) -> int:
    if i in ROUND_CONSTANTS_RECOVERED:
        return ROUND_CONSTANTS_RECOVERED[i]
    raise NotImplementedError(
        f"K[{i}] not yet recovered (only K[0] = "
        "0xd76aa478 stamped into head)."
    )


# =============================================================================
# Pending: F/G/H/I-style non-linear round function (MVP-9)
# =============================================================================

def round_function(A: int, B: int, C: int, D: int,
                   message_word: int, K_i: int, s_i: int,
                   iteration_index: int) -> tuple:
    """One MD5-style round; not yet recovered.

    Future MVP-9 will derive the F/G/H/I + modular-add structure from
    the body's confirmed boolean gates and emit it here.
    """
    raise NotImplementedError(
        "round_function not yet recovered (pending MVP-9: F/G/H/I + adder)."
    )


# =============================================================================
# Pending: padding scheme (MVP-10)
# =============================================================================

def pad_message(byte_values: Sequence[int]) -> list:
    """Pad the byte sequence into the head's input format; not yet recovered."""
    raise NotImplementedError(
        "Padding scheme not yet recovered (pending MVP-10)."
    )


# =============================================================================
# Top-level emit (raises until enough has been recovered to run end-to-end)
# =============================================================================

def emit_predict(s: str) -> int:
    """Pure Python prediction; will run end-to-end once all pieces are recovered."""
    bytes_in = encode(s)
    padded = pad_message(bytes_in)              # MVP-10
    A, B, C, D = INITIAL_STATE_LE
    for i in range(NUM_BODY_ITERATIONS + 1):
        k_i = K(i)                              # MVP-8
        s_i = SHIFT_SCHEDULE[i % len(SHIFT_SCHEDULE)]
        # The "message word" indexing is part of MVP-9.
        m_i = padded[i % len(padded)]
        A, B, C, D = round_function(A, B, C, D, m_i, k_i, s_i, i)
    digest_bytes = bytes_from_state(A, B, C, D)  # also pending
    return int(digest_bytes == TARGET_DIGEST_BYTES)


def bytes_from_state(A: int, B: int, C: int, D: int) -> bytes:
    """Pack the four 32-bit state words into 16 bytes (little-endian)."""
    out = bytearray()
    for w in (A, B, C, D):
        out.extend(w.to_bytes(4, "little"))
    return bytes(out)


# =============================================================================
# Verification harness against the original PyTorch model
# =============================================================================

def verify_against_model(model, samples) -> dict:
    """Run the emitted program alongside the original model on `samples`.

    For each sample we record (a) what the model returns, (b) what the
    emitted program produces (or which NotImplementedError it raised).

    Returns a dict with three fields: ``total``, ``model_results``,
    ``emit_status`` (one of {"ok", "not_implemented", "mismatch"}).
    """
    import torch
    rows = []
    for s in samples:
        x = torch.tensor([float(b) for b in encode(s)])
        with torch.no_grad():
            model_out = float(model(s).item()) if hasattr(model, "__call__") else None
        try:
            emit_out = emit_predict(s)
            status = "ok" if (model_out is None or emit_out == int(model_out)) else "mismatch"
        except NotImplementedError as e:
            emit_out = None
            status = f"not_implemented: {e}"
        rows.append((s, model_out, emit_out, status))
    return {
        "total": len(samples),
        "model_results": [(s, m) for s, m, _, _ in rows],
        "emit_status": [(s, st) for s, _, _, st in rows],
    }


if __name__ == "__main__":
    print(__doc__)
    print()
    print("Try:")
    print('  encode("bitter lesson")')
    print()
    print("encode('bitter lesson') =", encode("bitter lesson"))
